<?php

/**
 * @package     Qodehub\Slydepay
 * @link        https://github.com/qodehub/slydepay-php
 *
 * @author      Ariama O. Victor (ovac4u) <victorariama@qodehub.com>
 * @link        http://www.ovac4u.com
 *
 * @license     https://github.com/qodehub/slydepay-php/blob/master/LICENSE
 * @copyright   (c) 2018, QodeHub, Ltd
 */

namespace Qodehub\Slydepay\Api;

use Qodehub\Slydepay\Utility\CanCleanParameters;
use Qodehub\Slydepay\Utility\MassAssignable;

/**
 * ListPayOptions Class
 */
class ConfirmTransaction extends SendInvoice
{
    use MassAssignable;
    use CanCleanParameters;

    /**
     * {@inheritdoc}
     */
    protected $parametersRequired = [
    ];

    /**
     * {@inheritdoc}
     */
    protected $parametersOptional = [
        'transactionId',
        'orderCode',
        'payToken',
    ];

    /**
     * id Optional transaction id returned by the callback url as transac_id parameter.
     * This is optional if paytoken or orderCode is used
     *
     * @var string
     */
    protected $transactionId;

    /**
     * Optional Paytoken returned by Slydepay. This is optional if orderCode is used.
     *
     * @var string
     */
    protected $payToken;
    /**
     * Optional Your merchant order unique Id generated by/in your system.
     * This is optional if payToken is used
     *
     * @var string
     */
    protected $orderCode;

    /**
     * Construct for creating a new instance of this class
     *
     * @param array|string $data An array with assignable Parameters or an
     *                           Address or an addressID
     */
    public function __construct($data = null)
    {
        $this->massAssign($data);
    }

    /**
     * id Optional transaction id returned by the callback url as transac_id parameter.
     * This is optional if paytoken or orderCode is used
     *
     * @param  string $transactionId The transaction id
     * @return self
     */
    public function transactionId($transactionId)
    {
        return $this->setTransactionId($transactionId);
    }

    /**
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transactionId;
    }

    /**
     * @param string $transactionId
     *
     * @return self
     */
    public function setTransactionId($transactionId)
    {
        $this->transactionId = $transactionId;

        return $this;
    }

    /**
     * @return string
     */
    public function getPayToken()
    {
        return $this->payToken;
    }

    /**
     * @param string $payToken
     *
     * @return self
     */
    public function setPayToken($payToken)
    {
        $this->payToken = $payToken;

        return $this;
    }

    /**
     * @return string
     */
    public function getOrderCode()
    {
        return $this->orderCode;
    }

    /**
     * @param string $orderCode
     *
     * @return self
     */
    public function setOrderCode($orderCode)
    {
        $this->orderCode = $orderCode;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function run()
    {
        $this->propertiesPassRequired();

        return $this->_post(
            'transaction/confirm',
            $this->propertiesToArray()
        );
    }
}
